plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "Soporte Ingenieria Avanzada"
email: soporte@ingenieria-avanzada.com
description: ""
github:
  username: soporteiasa
swiftype:
  searchId: iXZyPokVfxFaBTvi64Y6
gitment:
    repo: blog
    client_id: 58d779884371191d06c9
    client_secret: d9651f116fab7b65d518252dde10e80cc465884c

url: "https://soporteiasa.github.io"
imgrepo: ""
